
manufacturer_names={"ACI":"Asus (ASUSTeK Computer Inc.)",
"ACR":"Acer America Corp.",
"ACT":"Targa",
"ADI":"ADI Corporation",
"AMW":"AMW",
"AOC":"AOC International (USA) Ltd.",
"API":"Acer America Corp.",
"APP":"Apple Computer, Inc.",
"ART":"ArtMedia",
"AST":"AST Research",
"AUO":"AU Optronics",
"BMM":"BMM",
"BNQ":"BenQ Corporation",
"BOE":"BOE Display Technology",
"CPL":"Compal Electronics, Inc. / ALFA",
"CPQ":"COMPAQ Computer Corp.",
"CTX":"CTX - Chuntex Electronic Co.",
"DEC":"Digital Equipment Corporation",
"DEL":"Dell Computer Corp.",
"DPC":"Delta Electronics, Inc.",
"DWE":"Daewoo Telecom Ltd",
"ECS":"ELITEGROUP Computer Systems",
"EIZ":"EIZO",
"EPI":"Envision Peripherals, Inc.",
"FCM":"Funai Electric Company of Taiwan",
"FUS":"Fujitsu Siemens",
"GSM":"LG Electronics Inc. (GoldStar Technology, Inc.)",
"GWY":"Gateway 2000",
"HEI":"Hyundai Electronics Industries Co., Ltd.",
"HIQ":"Hyundai ImageQuest",
"HIT":"Hitachi",
"HSD":"Hannspree Inc",
"HSL":"Hansol Electronics",
"HTC":"Hitachi Ltd. / Nissei Sangyo America Ltd.",
"HWP":"Hewlett Packard (HP)",
"HPN":"Hewlett Packard (HP)",
"IBM":"IBM PC Company",
"ICL":"Fujitsu ICL",
"IFS":"InFocus",
"IQT":"Hyundai",
"IVM":"Idek Iiyama North America, Inc.",
"KDS":"KDS USA",
"KFC":"KFC Computek",
"LEN":"Lenovo",
"LGD":"LG Display",
"LKM":"ADLAS / AZALEA",
"LNK":"LINK Technologies, Inc.",
"LPL":"LG Philips",
"LTN":"Lite-On",
"MAG":"MAG InnoVision",
"MAX":"Maxdata Computer GmbH",
"MEI":"Panasonic Comm. & Systems Co.",
"MEL":"Mitsubishi Electronics",
"MIR":"miro Computer Products AG",
"MTC":"MITAC",
"NAN":"NANAO",
"NEC":"NEC Technologies, Inc.",
"NOK":"Nokia",
"NVD":"Nvidia",
"OQI":"OPTIQUEST",
"PBN":"Packard Bell",
"PCK":"Daewoo",
"PDC":"Polaroid",
"PGS":"Princeton Graphic Systems",
"PHL":"Philips Consumer Electronics Co.",
"PRT":"Princeton",
"REL":"Relisys",
"SAM":"Samsung",
"SEC":"Seiko Epson Corporation",
"SMC":"Samtron",
"SMI":"Smile",
"SNI":"Siemens Nixdorf",
"SNY":"Sony Corporation",
"SPT":"Sceptre",
"SRC":"Shamrock Technology",
"STN":"Samtron",
"STP":"Sceptre",
"TAT":"Tatung Co. of America, Inc.",
"TRL":"Royal Information Company",
"TSB":"Toshiba, Inc.",
"UNM":"Unisys Corporation",
"VSC":"ViewSonic Corporation",
"WTC":"Wen Technology",
"ZCM":"Zenith Data Systems"}

ram_type={
	"20": "DDR",
	"21":"DDR2",
	"22":"DDR2 FB-DIMM",
	"24":"DDR3",
	"26":"DDR4"
}

form_factor={
"0":"Unknown",
"1":"Other",
"2":"SIP",
"3":"DIP",
"4":"ZIP",
"5":"SOJ",
"6":"Proprietary",
"7":"SIMM",
"8":"DIMM",
"9":"TSOP",
"10":"PGA",
"11":"RIMM",
"12":"SODIMM",
"13":"SRIMM",
"14":"SMD",
"15":"SSMP",
"16":"QFP",
"17":"TQFP",
"18":"SOIC",
"19":"LCC",
"20":"PLCC",
"21":"DDR2",
"22":"FPBGA",
"23":"LGA"
}

