# Generated by Django 4.0.5 on 2022-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('request_tags', models.CharField(choices=[('Self repair', 'Self Repair'), ('Request Technician', 'Request Technician')], default='Request Technician', max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
