# Generated by Django 4.0.5 on 2022-08-26 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='status',
            field=models.CharField(choices=[('OPENED', 'OPENED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='OPENED', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 26, 15, 50, 31, 712322)),
        ),
    ]
